# TOML format의 Air의 설정파일입니다. 

# Working directory
root = "."
tmp_dir = "tmp"

[build]
  # air 실행시 실행될 커맨드입니다. make도 이용할 수 있습니다.
  cmd = "make build-air"
  # cmd의 커맨드로 생성되는 binary파일이 위치할 곳입니다.
  bin = "tmp/app"

  # Customize binary.
  full_bin = "./tmp/app/engine"
  delay = 1000

  # Ignore these filename extensions or directories.
  exclude_dir = [ "tmp", "vendor" ]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false

  follow_symlink = false

  # Watch these filename extensions.
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]

  kill_delay = "0s"

  # This log file places in your tmp_dir.
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
