version: '3.9'

services:
  mariadb:
    image: mariadb:10.4.8
    command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ${DB_LOCAL_PATH}:/var/lib/mysql

  # mongodb:
  #   image: mongo:5.0
  #   container_name: mongoDB
  #   ports:
  #     - 27017:27017
  #   environment: 
  #       - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
  #       - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  #       - MONGO_INITDB_DATABASE=${DB_NAME}
  #       - MONGO_DATABASE_USERNAME=${DB_USERNAME}
  #       - MONGO_DATABASE_PASSWORD=${DB_PASSWORD}
  #   volumes: 
  #     - ${DB_LOCAL_PATH}:/data/db


