// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/CO88/go-ddd-boilerplate/config"
	"github.com/CO88/go-ddd-boilerplate/container"
	"github.com/CO88/go-ddd-boilerplate/user"
	"github.com/CO88/go-ddd-boilerplate/user/delivery/http"
	"github.com/CO88/go-ddd-boilerplate/user/repository"
	"github.com/CO88/go-ddd-boilerplate/user/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitailizeDIContainer(configuration *config.Configuration, conn *sql.DB) *container.DIContainer {
	userRespository := repository.NewUserRepository(conn)
	userUsecase := usecase.NewUserUsecase(configuration, userRespository)
	userHandler := http.NewUserHandler(userUsecase)
	diContainer := container.NewDIContainer(configuration, userHandler)
	return diContainer
}

// wire.go:

var MainSet = wire.NewSet(container.NewDIContainer, user.UserSet)
