// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/CO88/go-ddd-boilerplate/api"
	"github.com/CO88/go-ddd-boilerplate/user/delivery/http"
	"github.com/CO88/go-ddd-boilerplate/user/repository/mysql"
	"github.com/CO88/go-ddd-boilerplate/user/usecase"
	"time"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitailizeHandler(dbConn *sql.DB, timeout time.Duration) api.ApiHandler {
	userRespository := mysql.NewUserRepository(dbConn)
	userUsecase := usecase.NewUserUsecase(userRespository, timeout)
	apiHandler := http.NewUserHandler(userUsecase)
	return apiHandler
}
